---
- name: Launch instance
  ec2:
    key_name: "{{ ec2_keypair_name }}"
    image: "{{ ec2_ami_id }}"
    instance_type: "{{ ec2_instance_type }}"
    instance_profile_name: "{{ ec2_iam_role }}"
    wait: true
    region: "{{ aws_region }}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"    
  register: ec2